# Generated by Django 5.0.2 on 2024-02-24 08:04

import autoslug.fields
import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('priority', models.FloatField(default=0, null=True)),
                ('title', models.CharField(max_length=150, null=True, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='title')),
                ('img', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, max_length=5000, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='Product/category/img')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, null=True, unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=250, null=True)),
                ('description_html', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('additional_information_html', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.FloatField(null=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('_sl', models.IntegerField(default=0, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, max_length=5000, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='Product/productImage/image')),
                ('is_feature', models.BooleanField(default=False, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.product')),
            ],
        ),
    ]
