# Generated by Django 5.0.2 on 2024-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.FloatField(default=0, null=True),
        ),
    ]
