# Generated by Django 5.0.2 on 2024-02-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_id_alter_productimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
