# Generated by Django 5.0.2 on 2024-02-26 17:06

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_id_alter_productimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='Product/productImage/image'),
        ),
    ]
