# Generated by Django 5.0.2 on 2024-02-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_details',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
