# Generated by Django 5.0.2 on 2024-03-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_size_size_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='polo_size_details',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='shirt_size_details',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
