# Generated by Django 5.0.2 on 2024-02-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productsizevarient_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizevarient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productsizevarient',
            name='updated_at',
        ),
    ]
