# Generated by Django 5.0.2 on 2024-02-24 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PERCIAL_PAID', 'Partial Paid')], default='unpaid', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESS', 'Process'), ('SHIFT', 'Shift'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('Products', models.JSONField(blank=True, null=True)),
                ('billing_address', models.JSONField(blank=True, null=True)),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodPurchaseProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.FloatField(null=True)),
                ('others_info', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order', to='order.codorder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_product', to='product.product')),
            ],
        ),
    ]
