# Generated by Django 5.0.2 on 2024-02-29 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_codorder_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codpurchaseproduct',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='order.codorder'),
        ),
    ]
